### ISSUE TITLE
Files are not created properly on first startup

### ISSUE THREAD

**Issue by SamB440** [SamB440/RPGRegions#3]
The files are not created properly on first startup.
`
[18:15:31 WARN]: java.io.IOException: The system cannot find the path specified
[18:15:31 WARN]:        at java.io.WinNTFileSystem.createFileExclusively(Native
Method)
[18:15:31 WARN]:        at java.io.File.createNewFile(Unknown Source)
[18:15:31 WARN]:        at com.SamB440.RPG.Regions.Main.addFiles(Main.java:92)
[18:15:31 WARN]:        at com.SamB440.RPG.Regions.Main.onEnable(Main.java:37)
[18:15:31 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlug
in.java:264)
[18:15:31 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(
JavaPluginLoader.java:337)
[18:15:31 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(Si
mplePluginManager.java:403)
[18:15:31 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlu
gin(CraftServer.java:381)
[18:15:31 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlu
gins(CraftServer.java:330)
[18:15:31 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(Minec
raftServer.java:422)
[18:15:31 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(Minec
raftServer.java:383)
[18:15:31 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(Minec
raftServer.java:338)
[18:15:31 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(De
dicatedServer.java:272)
[18:15:31 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(Min
ecraftServer.java:545)
[18:15:31 WARN]:        at java.lang.Thread.run(Unknown Source)
`

**Comment by SamB440** [comment]
Fixed in [commit](a1a8117013865cb53aa1fec5da7b8666382f6ca5)
